import assert from "node:assert"
import { scoreLaptops } from "./scoring"
import type { QuizAnswers, ScorableLaptop } from "./types"

// ── Mock laptops ──
// 5 laptops with deliberately varied specs to exercise scoring paths

const mockLaptops: ScorableLaptop[] = [
  {
    id: "budget-1",
    brand: "Acer",
    model: "Aspire 5",
    variant: "A515-45",
    price: 400,
    currency: "USD",
    region: "US",
    url: null,
    affiliateUrl: null,
    os: "windows",
    cpuBrand: "amd",
    cpuFamily: "Ryzen 5",
    cpuGeneration: "5500U",
    cpuCores: 6,
    gpuType: "integrated",
    gpuModel: "Radeon Graphics",
    gpuVRAM: null,
    ramAmount: 8,
    ramUpgradeable: true,
    storageAmount: 256,
    storageType: "SSD",
    storageExpandable: true,
    displaySize: 15.6,
    displayResolution: "1920x1080",
    displayRefreshRate: 60,
    displayPanelType: "IPS",
    displayBrightness: 250,
    displayColorGamut: "45% NTSC",
    displayTouch: false,
    batteryCapacity: 42,
    batteryLife: 6,
    weight: 1.8,
    buildMaterial: "plastic",
    webcamQuality: "720p",
    ports: ["usb-a", "hdmi", "usb-c"],
    wireless: "Wi-Fi 6",
    securityFeatures: ["tpm"],
    keyboardBacklit: false,
    isTouchscreen: false,
    isRefurbished: false,
    isActive: true,
    isPopular: true,
    imageUrl: null,
    reviewScore: 7.5,
    notes: null,
    retailers: [],
  },
  {
    id: "mid-gaming-1",
    brand: "Lenovo",
    model: "Legion 5",
    variant: "15ACH6",
    price: 800,
    currency: "USD",
    region: "US",
    url: null,
    affiliateUrl: null,
    os: "windows",
    cpuBrand: "amd",
    cpuFamily: "Ryzen 7",
    cpuGeneration: "5800H",
    cpuCores: 8,
    gpuType: "dedicated",
    gpuModel: "RTX 3050",
    gpuVRAM: 4,
    ramAmount: 16,
    ramUpgradeable: true,
    storageAmount: 512,
    storageType: "SSD",
    storageExpandable: true,
    displaySize: 15.6,
    displayResolution: "1920x1080",
    displayRefreshRate: 120,
    displayPanelType: "IPS",
    displayBrightness: 300,
    displayColorGamut: "100% sRGB",
    displayTouch: false,
    batteryCapacity: 60,
    batteryLife: 5,
    weight: 2.4,
    buildMaterial: "plastic",
    webcamQuality: "720p",
    ports: ["usb-a", "hdmi", "usb-c", "ethernet"],
    wireless: "Wi-Fi 6",
    securityFeatures: ["tpm"],
    keyboardBacklit: true,
    isTouchscreen: false,
    isRefurbished: false,
    isActive: true,
    isPopular: true,
    imageUrl: null,
    reviewScore: 8.5,
    notes: null,
    retailers: [],
  },
  {
    id: "premium-1",
    brand: "Apple",
    model: "MacBook Pro",
    variant: "14-inch M3 Pro",
    price: 2000,
    currency: "USD",
    region: "US",
    url: null,
    affiliateUrl: null,
    os: "macos",
    cpuBrand: "apple",
    cpuFamily: "Apple Silicon",
    cpuGeneration: "M3 Pro",
    cpuCores: 12,
    gpuType: "dedicated",
    gpuModel: "M3 Pro (18-core)",
    gpuVRAM: 18,
    ramAmount: 36,
    ramUpgradeable: false,
    storageAmount: 1024,
    storageType: "SSD",
    storageExpandable: false,
    displaySize: 14.2,
    displayResolution: "3024x1964",
    displayRefreshRate: 120,
    displayPanelType: "mini-LED",
    displayBrightness: 600,
    displayColorGamut: "P3",
    displayTouch: false,
    batteryCapacity: 70,
    batteryLife: 12,
    weight: 1.6,
    buildMaterial: "aluminum",
    webcamQuality: "1080p",
    ports: ["usb-c", "hdmi", "magsafe"],
    wireless: "Wi-Fi 6E",
    securityFeatures: ["touch-id"],
    keyboardBacklit: true,
    isTouchscreen: false,
    isRefurbished: false,
    isActive: true,
    isPopular: true,
    imageUrl: null,
    reviewScore: 9.2,
    notes: null,
    retailers: [],
  },
  {
    id: "ultrabook-1",
    brand: "Dell",
    model: "XPS 13",
    variant: "9315",
    price: 1200,
    currency: "USD",
    region: "US",
    url: null,
    affiliateUrl: null,
    os: "windows",
    cpuBrand: "intel",
    cpuFamily: "Core i7",
    cpuGeneration: "1250U",
    cpuCores: 10,
    gpuType: "integrated",
    gpuModel: "Iris Xe",
    gpuVRAM: null,
    ramAmount: 16,
    ramUpgradeable: false,
    storageAmount: 512,
    storageType: "SSD",
    storageExpandable: false,
    displaySize: 13.4,
    displayResolution: "1920x1200",
    displayRefreshRate: 60,
    displayPanelType: "OLED",
    displayBrightness: 500,
    displayColorGamut: "100% DCI-P3",
    displayTouch: true,
    batteryCapacity: 52,
    batteryLife: 10,
    weight: 1.2,
    buildMaterial: "aluminum",
    webcamQuality: "720p",
    ports: ["usb-c"],
    wireless: "Wi-Fi 6E",
    securityFeatures: ["fingerprint"],
    keyboardBacklit: true,
    isTouchscreen: true,
    isRefurbished: false,
    isActive: true,
    isPopular: true,
    imageUrl: null,
    reviewScore: 8.8,
    notes: null,
    retailers: [],
  },
  {
    id: "budget-gaming-1",
    brand: "HP",
    model: "Victus 15",
    variant: "fa0031nr",
    price: 650,
    currency: "USD",
    region: "US",
    url: null,
    affiliateUrl: null,
    os: "windows",
    cpuBrand: "intel",
    cpuFamily: "Core i5",
    cpuGeneration: "12450H",
    cpuCores: 8,
    gpuType: "dedicated",
    gpuModel: "GTX 1650",
    gpuVRAM: 4,
    ramAmount: 8,
    ramUpgradeable: true,
    storageAmount: 512,
    storageType: "SSD",
    storageExpandable: true,
    displaySize: 15.6,
    displayResolution: "1920x1080",
    displayRefreshRate: 60,
    displayPanelType: "IPS",
    displayBrightness: 250,
    displayColorGamut: "45% NTSC",
    displayTouch: false,
    batteryCapacity: 48,
    batteryLife: 4.5,
    weight: 2.3,
    buildMaterial: "plastic",
    webcamQuality: "720p",
    ports: ["usb-a", "hdmi", "usb-c", "ethernet"],
    wireless: "Wi-Fi 5",
    securityFeatures: ["tpm"],
    keyboardBacklit: false,
    isTouchscreen: false,
    isRefurbished: false,
    isActive: true,
    isPopular: false,
    imageUrl: null,
    reviewScore: 7.0,
    notes: null,
    retailers: [],
  },
]

// ── Student quiz answers with $500–$1500 budget ──
const studentAnswers: QuizAnswers = {
  region: "US",
  useCase: "student",
  budgetMin: 500,
  budgetMax: 1500,
  os: null,
  cpuBrand: null,
  minRam: null,
  minStorage: null,
  gpu: null,
  battery: "high",
  portability: "balanced",
  displaySize: null,
  displayQuality: [],
  gaming: null,
  upgradeability: null,
  buildQuality: null,
  ports: [],
  webcam: null,
  security: [],
  refurbished: null,
}

// ── Assertions ──

// 1. Basic scoring run
const results = scoreLaptops(mockLaptops, studentAnswers)

assert.ok(results.length > 0, "Should return non-empty results")
assert.ok(
  results.every(r => r.matchScore >= 0 && r.matchScore <= 100),
  "All scores in 0-100 range",
)
assert.ok(results[0].matchReasons.length > 0, "Top result has match reasons")

// 2. Budget filter — all returned laptops within $500–$1500
assert.ok(
  results.every(r => r.price >= 500 && r.price <= 1500),
  `All results within $500–$1500 budget (got prices: ${results.map(r => `$${r.price}`).join(", ")})`,
)

// 3. GPU filter — only dedicated-GPU laptops when filter is applied
const dedicatedAnswers: QuizAnswers = { ...studentAnswers, gpu: "dedicated" }
const gpuFiltered = scoreLaptops(mockLaptops, dedicatedAnswers)

assert.ok(gpuFiltered.length > 0, "GPU-filtered results should not be empty")
assert.ok(
  gpuFiltered.every(r => r.gpuType === "dedicated"),
  `All GPU-filtered results should have dedicated GPU (got: ${gpuFiltered.map(r => `${r.brand} ${r.model} (${r.gpuType})`).join(", ")})`,
)

// ── Summary ──
console.log(`✓ scoring demo passed — ${results.length} results, top match: ${results[0].matchScore}%`)
